# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ideal_group_size', models.IntegerField()),
                ('allow_projects', models.BooleanField()),
                ('allow_voting', models.BooleanField()),
                ('participants', models.CharField(max_length=2000)),
                ('project_ideas', models.CharField(max_length=2000)),
                ('groups', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='org_Events',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='part_Events',
            field=models.CharField(max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
    ]
