# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180214_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='null', max_length=2000),
        ),
    ]
