# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180215_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_Events',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='part_Events',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=260),
        ),
    ]
