# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180215_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000)),
                ('ratings', models.CharField(default='', max_length=2000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Event')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='U2P_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Project')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User')),
            ],
        ),
    ]
