# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_project_u2p_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventID',
            field=models.CharField(default='avvDr', max_length=10),
        ),
    ]
