# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_event_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.CharField(max_length=10),
        ),
    ]
