# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.CharField(max_length=10),
        ),
    ]
