# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20180319_1536'),
        ('mainApp', '0008_auto_20180319_2046'),
    ]

    operations = [
    ]
