# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_merge_20180330_1520'),
        ('mainApp', '0009_merge_20180326_1948'),
    ]

    operations = [
    ]
