# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_merge_20180404_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='project_ideas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org_Events',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='mainApp.User'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='mainApp.User'),
        ),
    ]
