# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20180404_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Project')),
                ('users', models.ManyToManyField(related_name='group_participants', to='mainApp.User')),
            ],
        ),
    ]
