# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_u2p_relation_event'),
        ('mainApp', '0012_group'),
    ]

    operations = [
    ]
